# Generated by Django 3.0.2 on 2020-07-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200718_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
